/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/wraith/human.gltf -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Human(props) {
  const { nodes, materials } = useGLTF('/wraith/human.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Human.geometry} material={nodes.Human.material} rotation={[-0.003, 0.024, 0.046]} />
    </group>
  )
}

useGLTF.preload('/wraith/human.gltf')
