/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/wraith/wraith.gltf -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Wraith(props) {
  const { nodes, materials } = useGLTF('/wraith/wraith.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 33.483, 0.006]} scale={33.54}>
        <mesh geometry={nodes.jumpkit_1.geometry} material={materials.wraith_jumpkit_cyberninja} />
        <mesh geometry={nodes.eye_base_1.geometry} material={materials.wraith_eye_base} />
        <mesh geometry={nodes.head_1.geometry} material={materials.wraith_head} />
        <mesh geometry={nodes.body_1.geometry} material={materials.wraith_body_cyberninja} />
        <mesh geometry={nodes.gauntlet_1.geometry} material={materials.wraith_gauntlet_cyberninja} />
        <mesh geometry={nodes.helm_1.geometry} material={materials.wraith_helm_cyberninja} />
      </group>
    </group>
  )
}

useGLTF.preload('/wraith/wraith.gltf')
